# Site settings
title: "喜哥简历"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "付庭喜(Vincent Fu)"
resume_title:                   "已老实 求放过"

# 用于 _layouts/resume.html 中的联系按钮
resume_contact_email:           "3167089271@qq.com"

# 接下来的两项用于 _layouts/resume.html 中的 schema itemprops
resume_contact_telephone:       "111111111111"
resume_contact_address:         "云南 昆明"

resume_header_contact_info:     "云南 昆明 • 111111111111 • 3167089271@qq.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>郁闷的事情是，面对一个代码块，却不敢去修改。更糟糕的是，这个代码块还是自己写的。它在我的机器上可以很好运行！</p>"

# 使用“是”显示电子邮件联系按钮，
# 使用“否”显示“我不找工作”消息，
# 或完全删除 resume_looking_for_work 选项
# 留空
resume_looking_for_work:        "yes"

# 决定使用哪些部分
# 注释掉以隐藏
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# 恢复社交链接
# 取消注释您希望显示的选项，并添加您自己的 URL
resume_social_links:
  resume_github_url:            "https://github.com/futingx/resume"
  # resume_twitter_url:           "#"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "futingxi"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "futingxi"
  resume_website_url:           "https://futingx.github.io/"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# 注意：在本地编辑时，请记住在编辑此文件时重新启动
# Jekyll 服务器。对 _config.yml 的更改
# 仅在服务器启动时才会被识别
